using System;
using System.Drawing;
using System.IO;
using System.Reflection;
using Grasshopper.Kernel;
using Lama.Core.Application;

namespace Lama.Grasshopper.Components
{
	public class RunWithExeComponent : GH_Component
	{
		public RunWithExeComponent()
			: base(
				"RunWithExe",
				"RunExe",
				"Runs CalculiX with an input file. For CalculiX on Mac, specify the full path (e.g., /usr/local/bin/ccx or /opt/homebrew/bin/ccx)",
				"Lama",
				"Utils")
		{
		}

		protected override void RegisterInputParams(GH_InputParamManager pManager)
		{
			pManager.AddTextParameter("File", "File", "Path to the input file (.inp)", GH_ParamAccess.item);
			pManager.AddTextParameter("Executable", "Exe", GetExecutableParamDescription(), GH_ParamAccess.item);
			pManager[1].Optional = true;
		}

		private string GetExecutableParamDescription()
		{
			if (CalculixApplication.IsMacOS)
			{
				return "Path to CalculiX executable (optional, auto-detects if not provided). Examples: /usr/local/bin/ccx or /opt/homebrew/bin/ccx";
			}
			else if (CalculixApplication.IsWindows)
			{
				return "Path to CalculiX executable (optional, auto-detects if not provided). Example: C:\\CCX\\ccx.exe";
			}
			else
			{
				return "Path to CalculiX executable (optional, auto-detects if not provided). Example: /usr/bin/ccx";
			}
		}

		protected override void RegisterOutputParams(GH_OutputParamManager pManager)
		{
			pManager.AddTextParameter("StdOut", "Out", "Standard output from the process", GH_ParamAccess.item);
			pManager.AddTextParameter("StdErr", "Err", "Standard error from the process", GH_ParamAccess.item);
		}

		protected override void SolveInstance(IGH_DataAccess DA)
		{
			string inputFilePath = string.Empty;
			string exePath = string.Empty;

			// Get input file path
			if (!DA.GetData(0, ref inputFilePath))
			{
				DA.SetData(0, string.Empty);
				DA.SetData(1, string.Empty);
				AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Missing input file path");
				return;
			}

			// Validate input file exists
			if (!File.Exists(inputFilePath))
			{
				DA.SetData(0, string.Empty);
				DA.SetData(1, string.Empty);
				AddRuntimeMessage(GH_RuntimeMessageLevel.Error, $"Input file not found: {inputFilePath}");
				return;
			}

			// Check for .inp extension
			if (!inputFilePath.EndsWith(".inp", StringComparison.OrdinalIgnoreCase))
			{
				DA.SetData(0, string.Empty);
				DA.SetData(1, string.Empty);
				AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Input file must have .inp extension");
				return;
			}

			// Get executable path or auto-detect
			DA.GetData(1, ref exePath);
			
			if (string.IsNullOrWhiteSpace(exePath))
			{
				// Try to find CalculiX automatically
				exePath = CalculixApplication.FindCalculixExecutable();
				if (string.IsNullOrWhiteSpace(exePath))
				{
					DA.SetData(0, string.Empty);
					DA.SetData(1, string.Empty);
					string platformHint = CalculixApplication.IsMacOS 
						? " Common Mac paths: /usr/local/bin/ccx or /opt/homebrew/bin/ccx" 
						: " Install CalculiX and ensure it's in your PATH";
					AddRuntimeMessage(GH_RuntimeMessageLevel.Error, $"CalculiX executable not found.{platformHint}");
					return;
				}
				else
				{
					AddRuntimeMessage(GH_RuntimeMessageLevel.Remark, $"Auto-detected CalculiX at: {exePath}");
				}
			}

			// Validate executable exists
			if (!CalculixApplication.ValidateExecutable(exePath))
			{
				DA.SetData(0, string.Empty);
				DA.SetData(1, string.Empty);
				string platformHint = CalculixApplication.IsMacOS 
					? " Common Mac paths: /usr/local/bin/ccx or /opt/homebrew/bin/ccx" 
					: "";
				AddRuntimeMessage(GH_RuntimeMessageLevel.Error, $"Executable not found: {exePath}.{platformHint}");
				return;
			}

			// Run CalculiX using the Core Application class
			try
			{
				string workingDirectory = Path.GetDirectoryName(inputFilePath);
				int exitCode = CalculixApplication.RunCalculix(exePath, inputFilePath, workingDirectory);

				// Read output files generated by CalculiX
				string baseFileName = Path.GetFileNameWithoutExtension(inputFilePath);
				string outputPath = Path.Combine(workingDirectory, baseFileName + ".dat");
				string errorPath = Path.Combine(workingDirectory, baseFileName + ".sta");

				string stdOut = File.Exists(outputPath) ? File.ReadAllText(outputPath) : $"Exit code: {exitCode}";
				string stdErr = File.Exists(errorPath) ? File.ReadAllText(errorPath) : string.Empty;

				DA.SetData(0, stdOut);
				DA.SetData(1, stdErr);

				if (exitCode == 0)
				{
					AddRuntimeMessage(GH_RuntimeMessageLevel.Remark, "CalculiX execution completed successfully");
				}
				else
				{
					AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, $"CalculiX exited with code: {exitCode}");
				}
			}
			catch (Exception ex)
			{
				DA.SetData(0, string.Empty);
				DA.SetData(1, string.Empty);
				AddRuntimeMessage(GH_RuntimeMessageLevel.Error, $"Failed to run CalculiX: {ex.Message}");
			}
		}

		protected override Bitmap Icon
		{
			get
			{
				try
				{
					var assembly = Assembly.GetExecutingAssembly();
					var resourceName = "Lama.Lama.Grasshopper.Resources.Lama_24_24.png";
					using (Stream stream = assembly.GetManifestResourceStream(resourceName))
					{
						if (stream != null)
						{
							return new Bitmap(stream);
						}
					}
				}
				catch
				{
					// Return null if icon cannot be loaded
				}
				return null;
			}
		}

		public override Guid ComponentGuid => new Guid("e5e3f4f9-9a6a-4c05-9da3-b5cc6b61a7a3");
	}
}
